### ISSUE TITLE
`htmld` seems broken, can't compile chandler2

### ISSUE THREAD

**Issue by hails** [forbjok/chandler2#2]
I'm trying to compile `chandler2` on Linux but I get an error when `dub` compiles `htmld`

`dmd` version:
```
DMD64 D Compiler v2.079.0
Copyright (C) 1999-2018 by The D Language Foundation, All Rights Reserved written by Walter Bright
```

`dub` version:
```
DUB version 1.8.0, built on Mar  3 2018
```

`dub build` output:
```
Fetching jsonserialized 0.2.1 (getting selected version)...
Fetching std_data_json 0.18.2 (getting selected version)...
Fetching tinyendian 0.1.2 (getting selected version)...
Fetching taggedalgebraic 0.10.9 (getting selected version)...
Fetching dyaml 0.6.5 (getting selected version)...
Fetching dstatus 0.0.3 (getting selected version)...
Fetching reurl 0.0.2 (getting selected version)...
Fetching htmld 0.2.19 (getting selected version)...
Fetching yamlserialized 0.3.0 (getting selected version)...
Fetching dunit 1.0.14 (getting selected version)...
Package taggedalgebraic can be upgraded from 0.10.9 to 0.10.11.
Use "dub upgrade" to perform those changes.
Performing "debug" build using /usr/bin/dmd for x86_64.
dstatus 0.0.3: building configuration "library"...
dunit 1.0.14: building configuration "library"...
tinyendian 0.1.2: building configuration "library"...
dyaml 0.6.5: building configuration "library"...
htmld 0.2.19: building configuration "library"...
../../.dub/packages/htmld-0.2.19/htmld/src/html/dom.d(937,47): Error: cannot implicitly convert expression theAllocator() of type RCIAllocator to std.experimental.allocator.IAllocator
../../.dub/packages/htmld-0.2.19/htmld/src/html/dom.d(1001,36): Error: cannot implicitly convert expression theAllocator() of type RCIAllocator to std.experimental.allocator.IAllocator
/usr/bin/dmd failed with exit code 1.
```

**Comment by hails** [comment]
@forbjok

**Comment by forbjok** [comment]
Yep, I'm aware of this issue.
It's caused by a breaking change in DMD 2.079 that breaks htmld.
That particular error is fixed in htmld's master branch (https://github.com/eBookingServices/htmld/commit/b0c2fda585c97ca6d45f8df8757ab08c72a1d40b), but the fix is not yet in the latest released version.

It also seems like the current master branch of htmld has introduced its own breaking changes that will require changes in my code as well.
I'll see if I can look into that tomorrow.

For the time being, it should compile fine with LDC2 v1.8.0 (latest) on Windows and 1.7.0* on GNU/Linux.
The previous version of DMD should also work.

 \* The reason I say 1.7.0 on GNU/Linux, is because when I tried with 1.8.0 a few weeks ago on Arch Linux, it failed with an unhelpful linker error. I don't know what the cause is, but I'm guessing it's a Linux-specific bug in LDC 1.8.0. I reproduced the same error on two machines running separate Arch installs, and it works on the same machines when downgrading back to 1.7.0. This might also be specific to Arch for all I know.

**Comment by forbjok** [comment]
I've updated chandler2 to be compatible with the current master branch of htmld. (0.3.1 had breaking changes that required code changes)

Since the changes necessary to work with DMD v2.079 are not yet in a released version of htmld, I'm putting off merging it to master until htmld does a release.

For now, you can switch to the branch https://github.com/forbjok/chandler2/tree/dmd-2.079-fixes which uses the master branch of htmld. It should work fine with DMD 2.079 and LDC 1.8.0.
Once htmld releases a version with the necessary changes, I'll update the fix commit to use the released version and merge the changes into master.

**Comment by hails** [comment]
Thank you very much, @forbjok 
You're AWESOME!

I'm not at my computer, so I can't test rn.
Gonna update with more info when I get on there!
Thx!!!

**Comment by forbjok** [comment]
The fix has been rebased to use the final v0.3.2 release of htmld and merged into master.
Chandler 2 should now compile on the current D compilers at this time. (DMD v2.080 and LDC v1.9.0)

Tests are failing with htmld v0.3.0+, but this is due to a change in htmld causing attributes to be written unquoted. It should not cause a problem in most cases (unquoted attribute values are technically allowed in the HTML5 spec, even though it looks ugly and inconsistent), and hopefully can be fixed in a future version of htmld. At that point, the resulting HTML for existing saved threads can be regenerated with the rebuild function to restore attribute quotes.
